### ISSUE TITLE
Confusion regarding the methods 

### ISSUE THREAD

**Issue by sirmaG** [Rostlab/MetaDisorder#1]
MD is based on 5 methods, but we can only find 4 folders named like 4 of those methods

**Comment by juanmirocks** [comment]
Good to know. Anything new discovered? Did you contact the authors? The tool works as it is?

**Comment by juanmirocks** [comment]
Hi @sirmaG I guess the confusion was due to the 5th method, which indeed was not a disorder prediction method ?
