### ISSUE TITLE
MDCorrections for Errors

### ISSUE THREAD

**Issue by fsblu** [Rostlab/MetaDisorder#7]
I have created a new branch named MDCorrections, partially corrected code can be found there.

**Comment by juanmirocks** [comment]
:+1:

**Comment by juanmirocks** [comment]
@sirmaG any news?

**Comment by fsblu** [comment]
The tool is running

2016-02-02 13:32 GMT+01:00 Juan Miguel Cejuela notifications@github.com:

> @sirmaG https://github.com/sirmaG any news?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Rostlab/MetaDisorder/issues/7#issuecomment-178550836.

## 

---

İrem Uygur

GSM:  (+49) 01575 684 25 74
           (+90) 537484 04 71

Skype:irem.uygur
G-mail: iremuygur1@gmail.com

**Comment by sirmaG** [comment]
I fixed a lot of errors and add many missing files, so the tool is now running and the new version is on github :) The only thing is that there is still some problem with the ucon method, which has to be fixed.

**Comment by juanmirocks** [comment]
big congrats; will check tomorrow

**Comment by juanmirocks** [comment]
Congratulations again for your efforts. Last time you told me that one tool was still giving problems. Is this solved already? I would like to test everything this Thursday if possible.

**Comment by fsblu** [comment]
Hello,

Yesterday, I have pushed a missing dependency for the first method called
in the runMD script . The version in github does not address the directory
of the missing dependency yet, because when I correct the directory, I have
received other errors. I will take a lot at the error once more, but
honestly at that point I can not seem to solve the error, since I can not
understand what the problem is. Something with where to find the input,
where to put the output and delete the outputs is messing, as one of the
directories (I guess the one for the input) is again the developer´s
computer. I suggest taking a look at it together with Sirma, because I
think I spent enough time for it and I can not figure out what to do. For
the next errors, they might be relevant to the first error.

Regards

2016-02-09 22:02 GMT+01:00 Juan Miguel Cejuela notifications@github.com:

> Congratulations again for your efforts. Last time you told me that one
> tool was still giving problems. Is this solved already? I would like to
> test everything this Thursday if possible.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Rostlab/MetaDisorder/issues/7#issuecomment-182066850.

## 

---

İrem Uygur

GSM:  (+49) 01575 684 25 74
           (+90) 537484 04 71

Skype:irem.uygur
G-mail: iremuygur1@gmail.com

**Comment by juanmirocks** [comment]
Alright. Let me know if you need any help.

**Comment by fsblu** [comment]
I have commited the code with the corrected directories. Whoever, installs
it also needs a folder named perl5 in their computer. I do not know if
there is any more dependency missing in the project. There are still a lot
of errors. The rest of the errors are related to generated output files,
which are supposed to be deleted after their creation.

Sirma I guess set the root as the home folder. Therefore, please pull the
code when you are at the home directory.
How to run :  perl runMD.pl fasta=tmdfast.fasta

I do not know if we are receving the same errors.  Screen shots of my
errors.

2016-02-10 12:10 GMT+01:00 Juan Miguel Cejuela notifications@github.com:

> Alright. Let me know if you need any help.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Rostlab/MetaDisorder/issues/7#issuecomment-182319476.

## 

---

İrem Uygur

GSM:  (+49) 01575 684 25 74
           (+90) 537484 04 71

Skype:irem.uygur
G-mail: iremuygur1@gmail.com

**Comment by fsblu** [comment]
Hello,

Have you tried the code? Are you receiving extra errors?

Regards

2016-02-10 20:28 GMT+01:00 İrem Uygur iremuygur1@gmail.com:

> I have commited the code with the corrected directories. Whoever, installs
> it also needs a folder named perl5 in their computer. I do not know if
> there is any more dependency missing in the project. There are still a lot
> of errors. The rest of the errors are related to generated output files,
> which are supposed to be deleted after their creation.
> 
> Sirma I guess set the root as the home folder. Therefore, please pull the
> code when you are at the home directory.
> How to run :  perl runMD.pl fasta=tmdfast.fasta
> 
> I do not know if we are receving the same errors.  Screen shots of my
> errors.
> 
> 2016-02-10 12:10 GMT+01:00 Juan Miguel Cejuela notifications@github.com:
> 
> > Alright. Let me know if you need any help.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Rostlab/MetaDisorder/issues/7#issuecomment-182319476
> > .
> 
> ## 
> 
> ---
> 
> İrem Uygur
> 
> GSM:  (+49) 01575 684 25 74
>            (+90) 537484 04 71
> 
> Skype:irem.uygur
> G-mail: iremuygur1@gmail.com

## 

---

İrem Uygur

GSM:  (+49) 01575 684 25 74
           (+90) 537484 04 71

Skype:irem.uygur
G-mail: iremuygur1@gmail.com

**Comment by juanmirocks** [comment]
Hi Iremu. Thanks. Sorry I am having troubles with my computer now and brought it to repair. On ~Tuesday I will be able to catch up.

**Comment by juanmirocks** [comment]
@iremu checking this now. I am missing to see a howto install from the source in the README ?

**Comment by juanmirocks** [comment]
I close this issue, as it is not really an issue. Let's keep the communication in: https://github.com/Rostlab/MetaDisorder/issues/3
